backend/controllers/SettingsController.php
<?php
namespace backend\controllers;

use common\models\Category;
use common\models\Subcategory;
use common\models\User;
use Yii;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SettingsController extends Controller {
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $categories = Category::find()->all();
        $newcategory = new Category();
        if ($newcategory->load(Yii::$app->request->post()) && $newcategory->save()) {
            Yii::$app->session->setFlash('success', 'Category added successfully!');
            return $this->redirect(['settings/index']);
        }
        $newuser = new User();
        if ($newuser->load(Yii::$app->request->post()) && $newuser->create()) {
            Yii::$app->session->setFlash('success', 'User added successfully!');
            return $this->redirect(['settings/index']);
        }
        $usersDataProvider = new ActiveDataProvider([
            'query' => User::find(),
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);
        return $this->render('index', [
            'categories' => $categories,
            'newcategory' => $newcategory,
            'usersDataProvider' => $usersDataProvider,
            'newuser' => $newuser,
        ]);
    }

    public function actionCategory($id) {
        if (!$model = Category::findOne($id)) {
            Yii::$app->session->setFlash('error', 'Category can not be found!');
            return $this->redirect(['settings/index']);
        }
        if (Yii::$app->request->get('delete')) {
            try {
                if ($model->delete()) {
                    Yii::$app->session->setFlash('success', 'Category deleted successfully!');
                    return $this->redirect(['settings/index']);
                } else {
                    Yii::$app->session->setFlash('error', 'Category can not be deleted! Please delete its subcategories and related products first.');
                }
            } catch (Exception $e) {
                Yii::$app->session->setFlash('error', 'Category can not be deleted! Please delete its subcategories and related products first.');
            }
        }
        $newSub = new Subcategory();
        $newSub->category_id = $model->id;
        if ($newSub->load(Yii::$app->request->post()) && $newSub->save()) {
            $newSub = new Subcategory();
            Yii::$app->session->setFlash('success', 'Subcategory added successfully!');
        }
        $subs = Subcategory::find()->where('category_id = :id', [':id' => $model->id])->all();

        return $this->render('category', [
            'model' => $model,
            'newSub' => $newSub,
            'subs' => $subs,
        ]);
    }

    public function actionDeletesub($id) {
        if (!$model = Subcategory::findOne($id)) {
            Yii::$app->session->setFlash('error', 'Subcategory can not be found!');
            return $this->redirect(['settings/index']);
        }
        try {
            if ($model->delete()) {
                Yii::$app->session->setFlash('success', 'Subcategory deleted successfully!');
            } else {
                Yii::$app->session->setFlash('error', 'Subcategory can not be deleted! Please delete its related products first.');
            }
        } catch (Exception $e) {
            Yii::$app->session->setFlash('error', 'Category can not be deleted! Please delete its related products first.');
        }
        return $this->redirect(['settings/category', 'id' => $model->category_id]);
    }

    public function actionDeleteuser($id) {
        if (!$model = User::findOne($id)) {
            Yii::$app->session->setFlash('error', 'User can not be found!');
            return $this->redirect(['settings/index']);
        }
        if ($model->id == 1) {
            Yii::$app->session->setFlash('error', 'You can not delete the first admin user!');
            return $this->redirect(['settings/index']);
        }
        if ($model->delete()) {
            Yii::$app->session->setFlash('success', 'User deleted!');
        }
        return $this->redirect(['settings/index']);
    }
}

backend/views/settings/category.php
<?php

/* @var $this yii\web\View */
use kartik\grid\GridView;
use kartik\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = 'Category';
?>

<h4 class="center teal-text"><?= $model->title; ?></h4>
<div class="center margin-bottom-20">
    <?= Html::a('Delete', Url::toRoute(['settings/category']) . '/' . $model->id . '?delete=1', ['class' => 'waves-effect btn red']); ?>
</div>
<div class="card-panel white">
    <div class="card-content">
        <ul class="collection with-header">
            <li class="collection-header"><h4>Subcategories</h4></li>
            <?php if (count($subs) < 1) { ?>
                <li class="collection-item center">No subcategories available yet...</li>
            <?php } ?>
            <?php foreach ($subs as $sub) { ?>
                <li class="collection-item"><?= $sub->title ?>
                    <a href="<?= Url::toRoute(['settings/deletesub']) . '/' . $sub->id; ?>" class="secondary-content"><i class="material-icons red-text">delete</i></span>
                    </a>
                </li>
            <?php } ?>
        </ul>

        <?php
        $form = ActiveForm::begin([
            'id' => 'new-category',
        ]);
        ?>
        <?= $form->field($newSub, 'title'); ?>
        <div class="center">
            <?= Html::submitButton('<i class="material-icons left">add</i> Add Subcategory', ['class' => 'waves-effect waves-light btn', 'name' => 'login-button']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

backend/views/settings/index.php
<?php

/* @var $this yii\web\View */
use kartik\grid\GridView;
use kartik\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = 'Settings';
?>
<h4 class="center teal-text">Users</h4>
<div class="card-panel white">
    <div class="card-content responsive-table">
        <?php
        echo GridView::widget([
            'dataProvider' => $usersDataProvider,
            'tableOptions' => ['class' => 'highlight centered margin-bottom-20 responsive-table', 'id' => 'employee-list'],
            'responsive' => false,
            'responsiveWrap' => false,
            'columns' => [
                'id',
                'email',
                'typelabel',
                ['attribute' => 'created_at',
                    'format' => ['date', 'php:' . \common\components\Currency::dateFormat()]
                ],
                [
                    'class' => '\kartik\grid\ActionColumn',
                    'template' => '{delete}',
                    'buttons' => ['delete' => function ($url, $model) {
                        return Html::a('<span class="material-icons">delete</span>', ['settings/deleteuser/' . $model->id]);
                    }],
                ],
            ],
        ]);
        ?>

        <?php
        $form = ActiveForm::begin([
            'id' => 'new-user',
        ]);
        ?>
        <div class="row">
            <div class="col m4 s12">
                <?= $form->field($newuser, 'email'); ?>
            </div>
            <div class="col m4 s12">
                <?= $form->field($newuser, 'password')->passwordInput(); ?>
            </div>
            <div class="col m4 s12">
                <?= $form->field($newuser, 'type')->dropDownList([0 => 'Admin', 10 => 'Sales', 20 => 'Technical'], ['class' => 'material']); ?>
            </div>
        </div>
        <div class="center">
            <?= Html::submitButton('<i class="material-icons left">add</i> Add User', ['class' => 'waves-effect waves-light btn', 'name' => 'login-button']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<hr/>
<h4 class="center teal-text">Categories</h4>
<div class="card-panel white">
    <div class="card-content">
        <div class="collection">
            <?php if (count($categories) < 1) { ?>
                <a href="#" class="collection-item center">No categories available yet...</a>
            <?php } ?>
            <?php foreach ($categories as $category) { ?>
                <a href="<?= Url::toRoute(['settings/category']) . '/' . $category->id ?>" class="collection-item"><?= $category->title ?></a>
            <?php } ?>
        </div>

        <?php
        $form = ActiveForm::begin([
            'id' => 'new-category',
        ]);
        ?>
        <?= $form->field($newcategory, 'title'); ?>
        <div class="center">
            <?= Html::submitButton('<i class="material-icons left">add</i> Add Category', ['class' => 'waves-effect waves-light btn', 'name' => 'login-button']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>