frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Category;
use common\models\Offer;
use common\models\Product;
use common\models\Subcategory;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends Controller {

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex() {
        $products = Product::find()->limit(6)->all();
        $offers = Offer::find()->limit(15)->all();
        return $this->render('index', [
            'products' => $products,
            'offers'=>$offers,
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionCategory($id, $sub = null) {
        if (!$model = Category::findOne($id)) {
            throw new NotFoundHttpException();
        }
        if (!$subcategory = Subcategory::findOne($sub)) {
            $products = Product::find()->where(['category_id' => $id])->all();
        } else {
            $products = Product::find()->where(['subcategory_id' => $sub])->all();
        }
        return $this->render('category', [
            'model' => $model,
            'subcategory' => $subcategory,
            'products' => $products,
        ]);
    }
}

frontend/views/layouts/_footer.php
<footer class="page-footer blue">
    <div class="footer-copyright blue">
        <div class="container">
            © <?= date('Y') ?> PhoneShop
            <span class="grey-text text-lighten-4 right">Created by Ahmad Ginzarly</span>
        </div>
    </div>
</footer>

frontend/views/layouts/_nav.php
<?php
use yii\helpers\Url;

$categories = \common\models\Category::getArray();
?>

<nav class="blue">
    <div class="nav-wrapper container">
        <a href=" <?= Url::toRoute(['/site/index']); ?>" class="brand-logo">PhoneShop</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="<?= Url::toRoute(['/site/index']); ?>">Home</a></li>
            <?php foreach ($categories as $category) { ?>
                <li><a href="<?= Url::to(['site/category', 'id' => $category['id']]) ?>"><?= $category['title']; ?></a>
                </li>
            <?php } ?>
        </ul>
        <ul class="side-nav" id="mobile-demo">
            <li><a href="<?= Url::toRoute(['/site/index']); ?>">Home</a></li>
            <?php foreach ($categories as $category) { ?>
                <li>
                    <a href="<?= Url::to(['site/category', 'id' => $category['id']]) ?>"><?= $category['title']; ?></a>
                </li>
            <?php } ?>
        </ul>
    </div>
</nav>

frontend/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use frontend\assets\AppAsset;
use yii\helpers\Url;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <script>
        var BASE_URL = '<?= Url::base(true); ?>';
    </script>
</head>
<body>
<?php $this->beginBody() ?>

<?php
include '_nav.php';
?>


<main>
    <div class="container">
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<?php
include '_footer.php';
?>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>