common/models/Sale.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "sale".
 *
 * @property integer $id
 * @property integer $quantity
 * @property double $cost
 * @property string $note
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $product_id
 * @property integer $customer_id
 *
 * @property Customer $customer
 * @property Product $product
 */
class Sale extends \yii\db\ActiveRecord {
    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'sale';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['quantity', 'cost'], 'required'],
            [['quantity', 'created_at', 'updated_at', 'product_id', 'customer_id'], 'integer'],
            [['cost'], 'number'],
            [['note'], 'string'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => Product::className(), 'targetAttribute' => ['product_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'quantity' => 'Quantity',
            'cost' => 'Cost',
            'note' => 'Note',
            'created_at' => 'Date',
            'updated_at' => 'Updated At',
            'product_id' => 'Product',
            'customer_id' => 'Customer',
        ];
    }

    public function behaviors() {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer() {
        return $this->hasOne(Customer::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct() {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }

    public function getProductname() {
        if ($this->product) {
            return $this->product->title;
        }
        return 'N/A';
    }

    public function getCustomername() {
        if ($this->customer) {
            return $this->customer->name;
        }
        return 'N/A';
    }

    public function afterSave($insert, $changedAttributes) {
        if ($insert) {
            if ($product = Product::findOne($this->product_id)) {
                $product->sold += $this->quantity;
                $product->save();
            }
        }
        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}

backend/controllers/CustomersController.php
<?php
namespace backend\controllers;

use common\models\Customer;
use common\models\Sale;
use Yii;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class CustomersController extends Controller {
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Customer::find(),
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCustomer($id = null) {
        $model = new Customer();
        if ($id && $find = Customer::findOne($id)) {
            $model = $find;
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Customer saved successfully');
            return $this->redirect(['customers/index']);
        }
        return $this->render('_customer', [
            'model' => $model,
        ]);
    }

    public function actionView($id) {
        $model = Customer::findOne($id);
        $dataProvider = new ActiveDataProvider([
            'query' => Sale::find()->where(['customer_id' => $model->id]),
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);
        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDelete($id) {
        if ($model = Customer::findOne($id)) {
            try {
                if ($model->delete()) {
                    Yii::$app->session->setFlash('success', 'Customer deleted successfully!');
                } else {
                    Yii::$app->session->setFlash('error', 'Customer can not be deleted! It has related past orders!');
                }
            } catch (Exception $e) {
                Yii::$app->session->setFlash('error', 'Customer can not be deleted! It has related past orders!');
            }
        }
        return $this->redirect(['customers/index']);
    }


}

backend/controllers/SalesController.php
<?php
namespace backend\controllers;

use common\models\Customer;
use common\models\Product;
use common\models\Sale;
use common\models\Subcategory;
use Yii;
use yii\base\Exception;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SalesController extends Controller {
    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => Sale::find(),
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => ['defaultOrder' => ['id' => SORT_DESC]]
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSale($id = null) {
        $model = new Sale();
        $model->quantity = 1;
        if ($id && $find = Sale::findOne($id)) {
            $model = $find;
        }
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Sale saved successfully');
            return $this->redirect(['sales/index']);
        }
        return $this->render('_sale', [
            'model' => $model,
        ]);
    }

    public function actionCalculateCost($productId, $quantity) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $arr = ['cost' => 0];
        if ($product = Product::findOne($productId)) {
            $arr['available'] = $product->realAvailable();
            $cost = $product->price * $quantity;
            $arr['cost'] = $cost;
        }
        return $arr;
    }

    public function actionDelete($id) {
        if ($model = Customer::findOne($id)) {
            try {
                if ($model->delete()) {
                    Yii::$app->session->setFlash('success', 'Customer deleted successfully!');
                } else {
                    Yii::$app->session->setFlash('error', 'Customer can not be deleted! It has related past orders!');
                }
            } catch (Exception $e) {
                Yii::$app->session->setFlash('error', 'Customer can not be deleted! It has related past orders!');
            }
        }
        return $this->redirect(['customers/index']);
    }


}

backend/views/sales/_sale.php
<?php

/* @var $this yii\web\View */
use kartik\grid\GridView;
use kartik\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;

$this->title = 'Sales';
?>
    <h4 class="center teal-text"><?= $model->isNewRecord ? 'Add' : 'View'; ?> Sale</h4>
    <div class="card-panel white">
        <div class="card-content">
            <?php
            $form = ActiveForm::begin([
                'id' => 'sale-form',
            ]);
            ?>
            <?php
            if (!$model->isNewRecord) {
                echo $form->field($model, 'id')->textInput(['type' => 'number', 'disabled' => 'disabled']);
                ?>
                <div class="form-group">
                    <label class="control-label active">Product</label>
                    <?php if ($model->product_id) { ?>
                        <a href="<?= Url::toRoute('products/product') . '/' . $model->product_id; ?>">
                            <input type="text" class="form-control" value="<?= $model->productname ?>" disabled="disabled">
                        </a>
                    <?php } else { ?>
                        <input type="text" class="form-control" value="<?= $model->productname ?>" disabled="disabled">
                    <?php } ?>
                </div>
                <div class="form-group">
                    <label class="control-label active">Customer</label>
                    <?php if ($model->product_id) { ?>
                        <a href="<?= Url::toRoute('customers/customer') . '/' . $model->customer_id; ?>">
                            <input type="text" class="form-control" value="<?= $model->customername ?>" disabled="disabled">
                        </a>
                    <?php } else { ?>
                        <input type="text" class="form-control" value="<?= $model->customername ?>" disabled="disabled">
                    <?php } ?>
                </div>
                <div class="form-group">
                    <label class="control-label active">Quantity</label>
                    <input type="text" class="form-control" value="<?= $model->quantity ?>" disabled="disabled">
                </div>
                <div class="form-group">
                    <label class="control-label active">Cost</label>
                    <input type="text" class="form-control" value="<?= \common\components\Currency::format($model->cost) ?>" disabled="disabled">
                </div>
            <?php } else { ?>
                <?= $form->field($model, 'product_id')->widget(\kartik\select2\Select2::classname(), [
                    'data' => \common\models\Product::listAvailable(),
                    'options' => ['placeholder' => 'Select a product ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]); ?>
                <?= $form->field($model, 'customer_id')->widget(\kartik\select2\Select2::classname(), [
                    'data' => \common\models\Customer::listAll(),
                    'options' => ['placeholder' => 'Select a customer ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]); ?>
                <?= $form->field($model, 'quantity')->textInput(['type' => 'number']); ?>
                <?= $form->field($model, 'cost'); ?>
            <?php } ?>
            <?= $form->field($model, 'note')->textarea(['class' => 'materialize-textarea']) ?>


            <div class="center">
                <?= Html::submitButton($model->isNewRecord ? 'Add' : 'Edit', ['class' => 'waves-effect waves-light btn']) ?>
                <?php if (!$model->isNewRecord) { ?>
                    <?= Html::a('Delete', Url::base(true) . '/customers/delete/' . $model->id, ['class' => 'waves-effect waves-light btn red']) ?>
                <?php } ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

<?php
$this->registerJsFile("/js/sale.js", ['depends' => 'yii\web\JqueryAsset', 'position' => \yii\web\View::POS_END], 'sale-js');
?>

backend/views/sales/index.php
<?php

/* @var $this yii\web\View */
use kartik\grid\GridView;
use kartik\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = 'Sales';
?>
<h4 class="center teal-text">Sales</h4>
<div class="card-panel white">
    <div class="card-content responsive-table">
        <?php
        echo GridView::widget([
            'dataProvider' => $dataProvider,
            'tableOptions' => ['class' => 'highlight centered margin-bottom-20 responsive-table', 'id' => 'sales-list'],
            'responsive' => false,
            'responsiveWrap' => false,
            'columns' => [
                'id',
                [
                    'label' => 'Product',
                    'value' => function ($data) {
                        return $data->productname; // $data['name'] for array data, e.g. using SqlDataProvider.
                    },
                ],
                'quantity',
                [
                    'attribute' => 'cost',
                    'value'=> function($data){
                        return \common\components\Currency::format($data->cost);
                    },
                ],
                [
                    'attribute' => 'created_at',
                    'format' => ['date', 'php:' . \common\components\Currency::dateFormat()]
                ],
                [
                    'class' => '\kartik\grid\ActionColumn',
                    'template' => '{view}',
                    'buttons' => ['view' => function ($url, $model) {
                        return Html::a('<span class="material-icons">visibility</span>', ['sales/sale/' . $model->id]);
                    }],
                ],
            ],
        ]);
        ?>

        <div class="center">
            <?= Html::a('<i class="material-icons left">add</i> Add', ['sales/sale'], ['class' => 'waves-effect waves-light btn', 'name' => 'login-button']) ?>
        </div>
    </div>
</div>